server:
  port: 36318
  error:
    include-message: always
spring:
  application:
    name: ms-products
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: fkubis
    password: fkubis
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
