server:
  port: 0
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: authorization

jwt:
  secret: agunia

